### PR TITLE
WIP: DO NOT MERGE!

### PR DESCRIPTION
**Pull request by schmmd**
This PR is to test the build in Travis--DO NOT MERGE.

### CODE REVIEW

**Comment by matt-gardner** [comment]
https://stackoverflow.com/a/39162893/1467533

Try adding
```
env = PYTHONHASHSEED=2157
```
to `pytest.ini`.  That _should_ make the tests pass even with the change you made in your previous commit (and would be an improvement!).

**Comment by schmmd** [comment]
@matt-gardner no dice.  I think it sets the environment variable after python has been loaded, so PYTHONHASHCODE does not take effect.  Yikes, what a setup!

**Comment by matt-peters** [comment]
FWIW, you can specify environmental variables in .travis.yml:  https://docs.travis-ci.com/user/environment-variables/

**Comment by matt-gardner** [comment]
@matt-peters, that's a good idea.

**Comment by schmmd** [comment]
Yes, that's probably better than https://github.com/allenai/deep_qa/blob/master/build_tools/travis/test_script.sh#L13.  I'll try it out today if I have time.

**Comment by matt-gardner** [comment]
Oh, wait, yeah, we already do that, and that's why it works.  Not sure that setting it in .travis.yml actually buys us anything.  CI passes; the issue is that it's opaque and you can easily miss things if you're setting up the environment for yourself, not in CI.  Having a failing test is a good idea here, but I'm not sure that moving it from where it is in the script into .travis.yml helps with clarity.

**Pull request closed without merging**
