### PR TITLE
Removed scala code, moved python code to standard places

### PR DESCRIPTION
**Pull request by matt-gardner**
This is huge.  I would recommend just browsing the code corresponding to this commit, instead of looking through the "files changed".

### CODE REVIEW

**Comment by matt-gardner** [comment]
The place to browse the code is here: https://github.com/matt-gardner/deep_qa/tree/remove_scala_code.  I'll worry about fixing the travis config soon.

**Comment by nelson-liu** [comment]
looks like you need to update `pytest.ini` though

**Comment by matt-gardner** [comment]
I don't see `deep_qa/project` or `deep_qa/target` - what do you mean?

**Comment by nelson-liu** [comment]
maybe its just me but when i pull down the PR locally i see those two folders --- it doesnt show up on your branch so i wouldn't worry

**Comment by nelson-liu** [comment]
oh duh those are gitignored files used by sbt

**Pull request merged**
