### PR TITLE
Load best model before testing on test_files

### PR DESCRIPTION
**Pull request by bsharpataz**

### CODE REVIEW

**Comment by matt-gardner** [comment]
Did this actually work?

**Comment by bsharpataz** [comment]
haha, yes, sorry I wasn't more explicit in slack than just saying "yay for you"

**Comment by matt-gardner** [comment]
No, it's just that I missed the slack message due to confusion with all of my meetings today.  Thanks for trying this, and submitting the PR!

**Comment by bsharpataz** [comment]
no prob! thanks for like, solving my coding problem over slack while in a meeting :)

**Pull request merged**
