### PR TITLE
Seeing if clearing the session helps with Travis flakiness

### PR DESCRIPTION
**Pull request by matt-gardner**

### CODE REVIEW

**Comment by nelson-liu** [comment]
http://stackoverflow.com/a/35705890 seems relevant as well

**Comment by nelson-liu** [comment]
but wow, that worked and it was _crazy_ fast! thanks

**Comment by matt-gardner** [comment]
Fixes #270.

**Comment by nelson-liu** [comment]
merging this, thanks @matt-gardner

**Pull request merged**
